### ISSUE TITLE
Xperia 1 IV Doubled-input Tochscreen

### ISSUE THREAD

**Issue by Techwizz-somboo** [sailfishos-sony-nagara/main#60]
Sometimes when I turn on my screen from sleep, the touchscreen starts doubling any tap I do, making it impossible to swipe, making the UI feel as if it is unresponsive. Turning off the screen and turning it back on usually fixes it.

It also seems, after it's been booted for a few hours, it's more persistent when the problem occurs.

Here's a little video previewing the issue:

https://github.com/user-attachments/assets/d3c332f6-6efd-486a-8d82-7973af337e68

**Comment by rinigus** [comment]
Would be also good to know your device model.

**Comment by Techwizz-somboo** [comment]
Here are the logs, thanks!

[logs.tar.gz](https://github.com/user-attachments/files/23442595/logs.tar.gz)

I'll play around with your build of lineage from here, thank you!

**Comment by Techwizz-somboo** [comment]
> First, the logs that you provided do not have initialization of the device. I wonder if you enabled persistent logs as documented in https://github.com/sailfishos-sony-nagara/main/wiki/Getting-logs-on-Sailfish . Could be useful to get the logs from the start of the device as well - maybe there are issues with initialization. For that, just boot the phone and after all stabilized, grab the logs. Send them, please.

You are right, I did not enable persistent logs. I'll get those sent, thanks!

> Next, when you observe this issue, try to restart composer. Its a bit tricky and requires `ssh` to login. Before restarting composer, close all the apps. After that:
> 
> ```
> # as root
> pkill vendor.qti.hardware.display.composer
> pkill vendor.semc.hardware.display
> ```
> 
> At this moment screen will be black and not really starting up. Next, as a defaultuser, try to restart lipstick:
> 
> ```
> # as defaultuser
> systemctl  --user restart lipstick
> ```
> 
> Screen should lid up after a bit of time (few seconds). Try to use the phone for some time and see if it helped.

Cool, I'll try this, thank you again!

> Working hypothesis: HW composer didn't initialize properly on boot and required later reinit. We have this already during a boot and I had a workaround against it. Maybe something similar happens here.

Could having FDE enabled somehow interfere with this?

Some observations I've had after using it for a bit:

It seems both of these things fix it (temporarily):
* Eject and reinsert the sim tray (weird, could be placebo, but has worked every time so far)
* Turning on the screen using the volume keys

It seems the touchscreen will not work when it takes around 5 seconds to turn on, but when it turns on instantly, the touchscreen also works no problem.

**Comment by Techwizz-somboo** [comment]
At about 21:30 MST (04:30 UTC), the problem was occurring, at pretty much exactly 1 hour of uptime. 

[logs.tar.gz](https://github.com/user-attachments/files/23574368/logs.tar.gz)

**Comment by rinigus** [comment]
Very difficult to say. I haven't found anything in the logs that would jump out on me, unfortunately. Don't see how I could help here.

**Comment by rinigus** [comment]
ping. did this config change help?

**Comment by Techwizz-somboo** [comment]
Just seeing this, I'll try making time for it today

**Comment by Techwizz-somboo** [comment]
It looks to have fixed it to me, but I'll test it for more time to make sure.

How do I tell if I have limited Jolla store functionallity? It seems to all be working for me as far as I can tell.

```
[root@Xperia1IV defaultuser]# ssu s
Device registration status: not registered
Device model: Xperia 1 IV (xqct54 / xqct54)
Device UID: [redacted]
Release: 5.0.0.68
Domain: sales
Brand: Jolla
```

**Comment by rinigus** [comment]
Sorry, delayed reply. Looks like we don't have proper XQ-CT72 support as our device reports xqct54. This I have to look into. I will open a new issue regarding it and CC you to that.

As it reports XQCT54, it will have full Jolla Store access - not limited to just couple of applications.

Looks like this issue was resolved and I will close it. Solution: https://github.com/sailfishos-sony-nagara/main/issues/60#issuecomment-3643664151

However, I will ask you in that new issue one question regarding image that you used to flash SFOS.

**Comment by Techwizz-somboo** [comment]
The problem still seems to sometimes occur, but I think it is less frequent (I have not been daily-driving it recently, though, so can't say for sure).

**Comment by rinigus** [comment]
Pity! And I hoped that this rather simple solution works. Frankly, no idea where to resolve it as I don't even observe anything similar.

**Comment by Techwizz-somboo** [comment]
Unfortunately, swapping to your builds of Lineage and Sailfish OS did not fix the doubled touchscreen input. I also played around with it for quite a while in Lineage, Lineage did not seem to have the problem.

**Comment by rinigus** [comment]
I'll reopen it for visibility. After installing from my builds, did you perform updates? To enable double tap - as it seemed to help in frequency.

**Comment by Techwizz-somboo** [comment]
I've been checking on the phone every now and then for the past few days, so far have not seen the problem since updating. I'll let you know if I eventually see it again, but it is looking good.

**Comment by rinigus** [comment]
Fingers crossed :)

**Comment by Techwizz-somboo** [comment]
I've been playing with it on and off for 8 days, I have not experienced the double input bug. I think it's safe to close this.

**Comment by rinigus** [comment]
Great! Let's hope it will stay that way, thanks.
